### ISSUE TITLE
Might want to refactor POSSESS into HAVES, move some of the USE to LIKES

### ISSUE THREAD

**Issue by volodymyr-kushnir** [dasha-korotkykh/dariakorotkykh.com#36]
~It may be reasonable to move some of the **USE** things into **LIKES** if you really like them. Or you might want to introduce **SKILLS** block instead (which could later be split into "soft" and "hard" if you have any respect for that).~ Hold on, seems like **USE** block is pretty much legit.
**POSSESS** seems obvious as well. Okay, this one is a topic for discussion.

**Comment by dasha-korotkykh** [comment]
There goes additional FEAR and DON'T BELIEVE. JK, just had hard time actually figuring out above-mentioned.
