### ISSUE TITLE
Decide on the styling for events

### ISSUE THREAD

**Issue by volodymyr-kushnir** [dasha-korotkykh/dariakorotkykh.com#79]
As of now Binary Studio period includes 28 events. What kind of information do you want to show? _(dates, locations, number of participants, links to the photos on third party platforms or links to the self-hosted galleries, major takeaways from the event, etc.)_
![screenshot from 2019-02-26 18-31-47](https://user-images.githubusercontent.com/10290626/53429184-cb78b600-39f4-11e9-95a5-8d6205fa1616.png)

**Comment by volodymyr-kushnir** [comment]
<img width="1440" alt="screen shot 2019-03-04 at 12 12 12 am" src="https://user-images.githubusercontent.com/10290626/53702734-ceb7db80-3e12-11e9-8168-c132829d67d8.png">
Yeah, so far it looks like that. I think it'd be better to split that list by years, i.e. 2019, 2018, 2017, 2016 — this way we'll remove some of the noise. Then we could try to move date to the right, and then put number of participants next to the event name, and locations near the dates on the right. Not sure, have to iterate on split on years first.

**Comment by dasha-korotkykh** [comment]
I agree! Second option looks more readable and cleaner as well. So the years will be yet another foldable list or just a divider?

**Comment by volodymyr-kushnir** [comment]
Divider for now.
